Feature/sync options
bildvitta/vuex-offline pull request #12
Opened 2021-07-12 18:40 UTC by eliasassuncao

2021-07-12 22:12 UTC, DouglasCalora requested changes

2021-07-12 22:12 UTC, DouglasCalora commented on CHANGELOG.md
> +- exported function `MakeSync` to synchronize database data.
database data? meio redundante

2021-07-12 22:12 UTC, DouglasCalora commented on CHANGELOG.md
> +- pass custom sync options through the vuex-offline constructor.
"send" no lugar de "pass"

2021-07-12 22:12 UTC, DouglasCalora commented on src/index.js
> +      waitForLeadership: false,
pq waitForLeadershit é false?

2021-07-12 22:12 UTC, DouglasCalora commented on src/index.js
> +    }
espaço

2021-07-12 22:12 UTC, DouglasCalora commented on src/index.js
> +    let totalPendingByCollection = []
pq let? quando trabalhamos com com array/objeto conseguimos manipular sem alterar o valor de memoria da variavel.

2021-07-12 22:12 UTC, DouglasCalora commented on src/index.js
> +      const moduleOptions = (moduleByName.sync && moduleByName.sync.options) || {}
`moduleByName?.sync?.options || {}` não funciona?

2021-07-12 22:12 UTC, DouglasCalora commented on src/index.js
> +      const syncOptions = { ...defaultOptions, ...this.sync.options, ...moduleOptions, }
remover virgula do final

2021-07-12 22:12 UTC, DouglasCalora commented on src/index.js
> +      if (moduleByName.sync && moduleByName.sync.handler) {
msm coisa do optional chaining

2021-07-12 22:12 UTC, DouglasCalora commented on src/index.js
> +    return await Promise.all(promises)
return await é uma boa pratica no js standard?

2021-07-12 22:12 UTC, DouglasCalora commented on src/index.js
> +    return await Promise.all(promises)
e de qualquer forma este return da fn não vira uma promise?

2021-07-13 14:37 UTC, eliasassuncao commented on src/index.js
> +      waitForLeadership: false,
por conta da função `awaitInitialReplication`, pra ela funcionar presita `waitForLeadership` e `live` precisa ser false.

2021-07-13 14:38 UTC, eliasassuncao commented on CHANGELOG.md
> +- exported function `MakeSync` to synchronize database data.
removido o `data`

2021-07-13 14:39 UTC, eliasassuncao commented on CHANGELOG.md
> +- pass custom sync options through the vuex-offline constructor.
feito.

2021-07-13 14:39 UTC, eliasassuncao commented on src/index.js
> +    }
feito

2021-07-13 14:42 UTC, eliasassuncao commented on src/index.js
> +      const moduleOptions = (moduleByName.sync && moduleByName.sync.options) || {}
eu tentei já, dá erro
![image](https://user-images.githubusercontent.com/29342573/125472295-48ed8ffe-269b-4a2c-af22-5df3827ecaa3.png)

2021-07-13 14:43 UTC, eliasassuncao commented on src/index.js
> +    let totalPendingByCollection = []
feito.

2021-07-13 14:43 UTC, eliasassuncao commented on src/index.js
> +      const syncOptions = { ...defaultOptions, ...this.sync.options, ...moduleOptions, }
removido

2021-07-13 14:43 UTC, eliasassuncao commented on src/index.js
> +      if (moduleByName.sync && moduleByName.sync.handler) {
dá o erro respondido acima.

2021-07-13 14:52 UTC, eliasassuncao commented on src/index.js
> +    return await Promise.all(promises)
quero q a função `makeSync` seja assíncrona (`await makeSync(...)`), e só retorne quando todas promises forem resolvidas. como vc faria?

2021-07-13 21:17 UTC, eliasassuncao commented on src/index.js
> +    return await Promise.all(promises)
feito com base no https://eslint.org/docs/rules/no-return-await conforme alinhado discord

2021-07-16 17:46 UTC, DouglasCalora requested changes

2021-07-16 17:46 UTC, DouglasCalora commented on src/index.js
> +
remover espaço

2021-07-16 17:46 UTC, DouglasCalora commented on src/index.js
> +        if (!totalPending) {
se totalPending sempre inicializa com zero, ele nunca vai cair no if, vai? o.O

2021-07-16 17:49 UTC, eliasassuncao commented on src/index.js
> +        if (!totalPending) {
esta sendo negado.

2021-07-16 17:49 UTC, eliasassuncao commented on src/index.js
> +
feito

2021-07-16 18:08 UTC, caiotarifa approved these changes

2021-07-16 20:50 UTC, DouglasCalora approved these changes

2021-07-16 20:52 UTC, merged