Feature/fix-destroy-error
bildvitta/vuex-offline pull request #30
Opened 2022-04-28 18:41 UTC by felipegoulart

2022-04-28 18:44 UTC, eliasassuncao requested changes

2022-04-28 18:44 UTC, eliasassuncao commented on CHANGELOG.md
> +- Problema: não era disparado o erro para ser tratado na chamada da `action`, fazendo com que o erro não caisse no catch.
esse problema deveria estar na linha acima pra manter o padrão não? poderia melhorar a frase como algo
```md
- Adicionado `throw error` na tratativa de erros na action `destroy` para conseguir recuperar o erro.
```

2022-04-28 18:47 UTC, felipegoulart commented on CHANGELOG.md
> +- Problema: não era disparado o erro para ser tratado na chamada da `action`, fazendo com que o erro não caisse no catch.
Vou verificar o pattern do changelog e corrijo. A sua descrição ficou melhor

2022-04-29 16:26 UTC, DouglasCalora requested changes

2022-04-29 16:26 UTC, DouglasCalora commented on src/module/actions/destroy.js
> +      const document = await collection.findOne(id).exec()
aqui foi dado espaço no final da linha?

2022-04-29 16:33 UTC, felipegoulart commented on src/module/actions/destroy.js
> +      const document = await collection.findOne(id).exec()
foi na hora de remover uma linha. Passou despercebido na hora de subir

2022-04-29 16:40 UTC, eliasassuncao approved these changes

2022-04-29 16:41 UTC, DouglasCalora approved these changes

2022-04-29 16:43 UTC, merged